---
title: "Homework 6"
author: "Josephine Alford, Feben Asefaha"
date: "11/13/2017"
output: html_document
---

```{r setup, warning = FALSE, message = FALSE}

##loaded data from website, csv is too large to commit rn

library(tidyverse)
library(httr)
library(jsonlite)
library(plotly)
library(lubridate)
library(forcats)
library(stringr)
library(viridis)
library(ggplot2)
library(dplyr)

get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/9w7m-hzhe.json"

nyc_inspections = get_all_inspections(url) %>%
  bind_rows() 


knitr::opts_chunk$set(echo = TRUE)
```



```{r FA first plot_ly, warning = FALSE, message = FALSE}

##cleaning up and filtering out



##selecting and editing variables, filtering year and boro
nyc_grade_prop <- nyc_inspections %>% 
  as.data.frame(nyc_inspections) %>% 
  filter(grade %in% c("A", "B", "C"), boro != "Missing") %>% 
  separate(grade_date, into = c("grade_date", "takeaway"), sep = "T") %>%
  select(-takeaway) %>% 
  separate(grade_date, into = c("year", "month", "day"), sep = "-") %>% 
  rename(name = dba) %>% 
  na.omit(grade) %>% 
  mutate(score = as.numeric(score)) %>% 
  select(year, month, day, boro, name, score, grade) %>% 
  filter(year == "2017",
         month == "10")


dim(nyc_grade_prop)
str(nyc_grade_prop) 

##you can only do order on a vector?


#View(nyc_grade_prop)
dim(nyc_grade_prop)

 
##Plotly to show the distribution of scores per month (October here) per boro

nyc_grade_prop %>% 
  mutate(boro = fct_reorder(boro, score)) %>% 
  group_by(boro, name) %>% 
  plot_ly(y = ~score, color = ~boro, type = "box",
          colors = "Set2") 

##interactivity option: being able to change the month via drop down menu?

## need to remove boro values labeled as Missing!!!!!
#Josie: I added code above from lecture notes


##hover text should show Grade and restaurant name? ALso need to make points a lot smaller!

##Recall, higher scores are worse!




```

```{r FA plotly two, warning = FALSE, message = FALSE}

##cleaning up data for second plotly 

  nyc_grade_prop2 <- nyc_inspections %>% 
  as.data.frame(nyc_inspections) %>% 
  separate(grade_date, into = c("grade_date", "takeaway"), sep = "T") %>%
  select(-takeaway) %>% 
  separate(grade_date, into = c("year", "month", "day"), sep = "-") %>% 
  rename(name = dba) %>% 
  na.omit(grade) %>% 
  mutate(score = as.numeric(score),
         month = as.numeric(month)) %>% 
  select(camis, year, month, day, boro, name, score, grade, cuisine_description) %>% 
  filter(year == "2016",
         cuisine_description %in% c("Chicken", "Hamburgers", "Vegetarian")) %>%
  mutate(month = as.factor(month)) 

##cami is unique identifier, sum all scores from same day bc they belong to same inspection

##then remove duplicates

p <- nyc_grade_prop2 %>% 
  group_by(camis, month, day) %>% 
  mutate(total_score = sum(score)) %>% 
  select(-score) %>% 
  unique()

  
# graph comparing average scores of three cuisines in 2016
 q <- p %>% 
  group_by(month, cuisine_description) %>% 
  summarize(mean_score = mean(total_score)) %>% 
  ggplot(aes(x = month, y = mean_score, color = cuisine_description)) +
    geom_point() + geom_line() +
    theme(legend.position = "bottom")

  
  ggplotly(q)
  


##Need to change month column from numbers to Jan/Feb/Mar etc...! are factors
  
  ##Interactivity idea:  Plot two cuisines at a time to see who has lower (better) mean scores per month: Hamburgers v  Vegetarian, Chicken v Hamburgers, Hamburgers v Chicken (like three button choices)
  
  ##I have to relabel axes, add lines!


```



```{r last test plotly, warning = FALSE, message = FALSE}

##this is an experimental plot, to see if i could do it
##distributions of cuisines of Manhattan inspections over  2017
##supposed to be a bar plot


nyc_grade_prop3<- nyc_inspections %>% 
  as.data.frame(nyc_inspections) %>% 
  separate(grade_date, into = c("grade_date", "takeaway"), sep = "T") %>%
  select(-takeaway) %>% 
  separate(grade_date, into = c("year", "month", "day"), sep = "-") %>% 
  rename(name = dba) %>% 
  mutate(score = as.numeric(score)) %>% 
  select(camis, year, month, day, boro, name, score, cuisine_description, grade) %>% 
  group_by(camis, year, month, day) %>% 
  mutate(total_score = sum(score)) %>% 
  select(-score) %>% 
  filter(year == "2017",
         boro == "MANHATTAN") %>% 
  unique() 
  
  #View(nyc_grade_prop3)

  ##doesn't work right :/ this plot will likely be deleted, 
  nyc_grade_prop3 %>% 
  count(cuisine_description) %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, n)) %>% 
  plot_ly(x = ~cuisine_description, y = ~n, color = ~cuisine_description, type = "bar") 
  


```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

Josie
```{r Mice/Rats/Roaches, warning = FALSE, message = FALSE}
#Among restaurants with mice, roaches or flies in violation, show distribution of scores based on cuisine
nyc_inspections_jo = nyc_inspections %>%
  filter(grade %in% c("A", "B", "C"), boro != "Missing") %>% 
  mutate(borough = str_to_title(boro)) %>%
  mutate(score = as.integer(score)) %>%
  select(borough, cuisine_description, dba, score, grade, violation_description) %>%
  filter(score > '0') %>% #eliminate restaurants without an inspection (0) and those with -1
  filter(str_detect(violation_description, regex("mice", ignore_case = TRUE)) | str_detect(violation_description, regex("flies", ignore_case = TRUE)) | str_detect(violation_description, regex("roach", ignore_case = TRUE))) 
#top 10 cuisines 
top_cuisines = nyc_inspections_jo %>%
  count(cuisine_description, sort = TRUE) %>% 
  top_n(8) %>% 
  select(cuisine_description) 
#join nyc_inspections_jo and top_cuisines
nyc_cuisine_final = inner_join(nyc_inspections_jo, top_cuisines, by = "cuisine_description")

nyc_inspections_jo_plotly = nyc_cuisine_final %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, score)) %>%
  plot_ly(y = ~score, color = ~cuisine_description, type = "box",
          colors = "Set1")
nyc_inspections_jo_plotly

```
